### PR TITLE
Added optional param to convert to data uri

### PR DESCRIPTION
**Pull request by smolnikov**

### CODE REVIEW

**Comment by smolnikov** [comment]
@didikeke ping :)

**Comment by smolnikov** [comment]
@didikeke Hi there! Any ideas about this PR?

**Comment by didikeke** [comment]
@smolnikov 
merged and published to npm.

**Comment by didikeke** [comment]
@smolnikov sorry for replying so late.

**Comment by didikeke** [comment]
@smolnikov sorry for replying so late.

This lib was using for one of my site ( http://guguji.me ) to call the API of memobird printer.  Memobird is a mini printer( http://memobird.cn ,http://open.memobird.cn/ ).

I didn't realise the other way to use it :) 

The PR has been merged and published. Thank you~

**Pull request merged**
